@startuml
!define VALUE_OBJECT <..>
package "Domain Layer" #FFFFFF {

  VALUE_OBJECT Money
  class Money {
    - amt : BigDecimal
    - cur : Currency
    + Money(amt,cur)
    + add(Money) : Money
    + subtract(Money) : Money
    + multiply(factor,mode) : Money
    + isZero() : boolean
    + isPositive() : boolean
    + isNegative() : boolean
    + isLessThan(Money) : boolean
    + compareTo(Money) : int
    + abs() : Money
    + zero(Currency) : Money
    + of(amount,Currency) : Money
  }

  VALUE_OBJECT Currency
  class Currency <<utility>> {
    + {static} getInstance(code) : Currency
    + getDefaultFractionDigits() : int
    + getCurrencyCode() : String
  }

  Money ..> Currency : uses
}

note right of Money : Value Object:\nno identity,\nimmutable,\nself-validating
@enduml
